### ISSUE TITLE
Unauthorized client: `grant_type` is invalid

### ISSUE THREAD

**Issue by pellenbeck** [py-smart-gardena/py-smart-gardena#173]
I would like to use [gardena2mqtt](https://github.com/Domochip/gardena2mqtt) in my environment.
gardena2mqtt is transmitting the data from py-smart-gardena by MQTT and can be run inside a docker container.

gardena2mqtt imports the SmartSystem from py-smart-gardena (https://github.com/Domochip/gardena2mqtt/blob/master/gardena2mqtt.py) and is using the original functions.

After building the docker container I can find the following failure in container logs:

```
Traceback (most recent call last):
  File "/app/gardena2mqtt.py", line 210, in <module>
    smart_system.authenticate()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 115, in authenticate
    self.token = self.oauth_session.fetch_token(
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 429, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 402, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client) Unauthorized client: `grant_type` is invalid
```

I already checked the Gardena credentials and changed the password but the problem still the same.

Do you have an idea where to search for the problem?

**Comment by crazyfx1** [comment]
The error message suggest that you are using an old version of py-smart-gardena. Please update to a newer version and try again.

**Comment by Domochip** [comment]
Hi,

I've adjusted my code, so this issue can be closed now.
ref : https://github.com/Domochip/gardena2mqtt/issues/11
