### ISSUE TITLE
confusing error: simplejson.errors.JSONDecodeError

### ISSUE THREAD

**Issue by atommaki** [py-smart-gardena/py-smart-gardena#87]
I've got an exception after update_locations(). My code is simple like that:

```
smart_system = SmartSystem(email=g_email, password=g_pass, client_id=g_client)
smart_system.authenticate()
smart_system.update_locations()
```
I got the exception in the last call (update_locations):

```
Traceback (most recent call last):
  File "./gardenatest.py", line 22, in <module>
    smart_system.update_locations()
  File "/home/user/.local/lib/python3.8/site-packages/gardena/smart_system.py", line 217, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/home/user/.local/lib/python3.8/site-packages/gardena/smart_system.py", line 188, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/home/user/.local/lib/python3.8/site-packages/gardena/smart_system.py", line 162, in __response_has_errors
    r = response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
All what I could figure out (by checking/editing the mentioned `smart_system.py`) is I got `401` in the response. I don't really understand why, my user/pass/client_id are correct and I didn't get any error in the previous line in the authenticate() call.

Anyway this `401` response is not handled very well here.

**Comment by grm** [comment]
Hello, which version are you using ?

Jeremie

**Comment by grm** [comment]
And did you remake an application ? Sometims gardena invalidates
credentials and you have to create a new one ...

**Comment by atommaki** [comment]
Thanks for the tip, deleting my application key and generating a new one solved the problem. (I haven't seen any sign the key was invalid...)
The behavior/error message is still confusing...

**Comment by atommaki** [comment]
This is the problematic code in the `smart_system.py`:

```
    def __response_has_errors(self, response):
        if response.status_code not in (200, 202):
            try:
                r = response.json()
                if 'errors' in r:
                    msg = "{r['errors'][0]['title']} - {r['errors'][0]['detail']}"
                elif 'message' in r:
                    msg = f"{r['message']}"

                    if response.status_code == 403:
                        msg = f"{msg} (hint: did you 'Connect an API' in your Application?)"
                else:
                    msg = f"{r}"

            except JSONDecodeError:
                msg = response.content
```

I've got the exception when the response was `401` and the `response.content` was empty, therefore the json conversion didn't work. I don't understand why the `except JSONDecodeError` didn't work, when the exception is exactly that one:

```
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
(full traceback above)
